{{- $unmanagedNamespaceExists := include "unmanaged-resource-exists" (list "v1" "Namespace" "" .Values.serverlessOperator.subscription.spec.namespace .Release.Name .Capabilities.APIVersions) }}
{{- if and (eq $unmanagedNamespaceExists "false") .Values.serverlessOperator.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.serverlessOperator.subscription.spec.namespace }}
{{- end }}

