{{- if and .Values.orchestrator.enabled .Values.orchestrator.serverlessOperator.enabled }}
  {{- $knativeServing := lookup "operator.knative.dev/v1beta1" "KnativeServing" "knative-serving" "knative-serving" }}
  {{- if not $knativeServing }}
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
spec:
  controller-custom-certs:
    name: ""
    type: ""
  registry: {}
  {{- end }}

  {{- $knativeEventing := lookup "operator.knative.dev/v1beta1" "KnativeEventing" "knative-eventing" "knative-eventing" }}
  {{- if not $knativeEventing }}
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
spec:
  Registry: {}
  {{- end }}
{{- end }}
